/**
 * Lite API
 * lite api hotel booking api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * https://konfigthis.com
 * Do not edit the class manually.
 */


package com.konfigthis.nuitee.client.api;

import com.konfigthis.nuitee.client.ApiException;
import com.konfigthis.nuitee.client.model.Cancel400Response;
import com.konfigthis.nuitee.client.model.Cancel401Response;
import com.konfigthis.nuitee.client.model.Cancel500Response;
import com.konfigthis.nuitee.client.model.CancelResponse;
import com.konfigthis.nuitee.client.model.ListBookingsResponse;
import com.konfigthis.nuitee.client.model.Retrieve400Response;
import com.konfigthis.nuitee.client.model.RetrieveResponse;
import org.junit.Ignore;
import org.junit.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for BookingManagementApi
 */
@Ignore
public class BookingManagementApiTest {

    private final BookingManagementApi api = new BookingManagementApi();

    /**
     * Booking cancel
     *
     * This endpoint allows you to cancel a booking based on a booking ID. The refund amount is based on the cancellation policies. &lt;!-- theme: danger --&gt;
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void cancelTest() throws Exception {
        String bookingId = null;
        CancelResponse response = api.cancel(bookingId);
        // TODO: test validations
    }

    /**
     * Booking list
     *
     * List bookings by guestId
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listBookingsTest() throws Exception {
        String guestId = null;
        ListBookingsResponse response = api.listBookings(guestId);
        // TODO: test validations
    }

    /**
     * Booking retrieve
     *
     * This endpoint allows you to retrieve all the information for specific booking ID.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void retrieveTest() throws Exception {
        String bookingId = null;
        RetrieveResponse response = api.retrieve(bookingId);
        // TODO: test validations
    }

}
