/**
 *
 * Please note:
 * This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.konfigthis.nuitee.client.models

import com.konfigthis.nuitee.client.models.GetHotelRatesResponseDataInnerRoomTypesInnerRatesInner

import com.squareup.moshi.Json

/**
 * 
 *
 * @param roomTypeId 
 * @param maxOccupancy 
 * @param rates 
 */


data class GetHotelRatesResponseDataInnerRoomTypesInner (

    @Json(name = "roomTypeId")
    val roomTypeId: kotlin.String? = null,

    @Json(name = "maxOccupancy")
    val maxOccupancy: kotlin.Int? = null,

    @Json(name = "rates")
    val rates: kotlin.collections.List<GetHotelRatesResponseDataInnerRoomTypesInnerRatesInner>? = null

)

