/**
 *
 * Please note:
 * This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.konfigthis.nuitee.client.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param message 
 */


data class ListHotels401Response (

    @Json(name = "message")
    val message: kotlin.String? = null

)

