/**
 *
 * Please note:
 * This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.konfigthis.nuitee.client.models

import com.konfigthis.nuitee.client.models.PrebookResponseDataRoomTypesInnerRatesInnerCancellationPolicies
import com.konfigthis.nuitee.client.models.PrebookResponseDataRoomTypesInnerRatesInnerRetailRate

import com.squareup.moshi.Json

/**
 * 
 *
 * @param rateId 
 * @param name 
 * @param maxOccupancy 
 * @param retailRate 
 * @param cancellationPolicies 
 */


data class PrebookResponseDataRoomTypesInnerRatesInner (

    @Json(name = "rateId")
    val rateId: kotlin.String? = null,

    @Json(name = "name")
    val name: kotlin.String? = null,

    @Json(name = "maxOccupancy")
    val maxOccupancy: kotlin.Int? = null,

    @Json(name = "retailRate")
    val retailRate: PrebookResponseDataRoomTypesInnerRatesInnerRetailRate? = null,

    @Json(name = "cancellationPolicies")
    val cancellationPolicies: PrebookResponseDataRoomTypesInnerRatesInnerCancellationPolicies? = null

)

