/**
 *
 * Please note:
 * This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.konfigthis.nuitee.client.models

import com.konfigthis.nuitee.client.models.PrebookResponseData

import com.squareup.moshi.Json

/**
 * 
 *
 * @param `data` 
 * @param guestLevel guests loyalty level granting them discounts and benefit
 * @param sandbox 
 */


data class PrebookResponse (

    @Json(name = "data")
    val `data`: PrebookResponseData? = null,

    /* guests loyalty level granting them discounts and benefit */
    @Json(name = "guestLevel")
    val guestLevel: kotlin.Int? = null,

    @Json(name = "sandbox")
    val sandbox: kotlin.Boolean? = null

)

