/**
 *
 * Please note:
 * This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.konfigthis.nuitee.client.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param cancelTime 
 * @param amount 
 * @param type 
 */


data class PrebookResponseDataRoomTypesInnerRatesInnerCancellationPoliciesCancelPolicyInfosInner (

    @Json(name = "cancelTime")
    val cancelTime: kotlin.String? = null,

    @Json(name = "amount")
    val amount: java.math.BigDecimal? = null,

    @Json(name = "type")
    val type: kotlin.String? = null

)

