/**
 *
 * Please note:
 * This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.konfigthis.nuitee.client.models

import com.konfigthis.nuitee.client.models.BookResponseDataBookedRoomsInnerRateRetailRate

import com.squareup.moshi.Json

/**
 * 
 *
 * @param maxOccupancy 
 * @param retailRate 
 */


data class RetrieveResponseDataBookedRoomsInnerRate (

    @Json(name = "maxOccupancy")
    val maxOccupancy: kotlin.Int? = null,

    @Json(name = "retailRate")
    val retailRate: BookResponseDataBookedRoomsInnerRateRetailRate? = null

)

