/*
Lite API

Testing BookApiService

*/

// Code generated by Konfig (https://konfigthis.com);

package nuitee

import (
    "os"
    "context"
    "github.com/stretchr/testify/assert"
    "github.com/stretchr/testify/require"
    "testing"
    nuitee "github.com/konfig-dev/nuitee-lite-sdks/go"
)

func Test_nuitee_BookApiService(t *testing.T) {

    configuration := nuitee.NewConfiguration()
    apiKey := os.Getenv("API_KEY")
    configuration.Context = context.WithValue(configuration.Context, nuitee.ContextAPIKeys, map[string]nuitee.APIKey{
    "ApiKeyAuth": {Key: apiKey},
    })
    apiClient := nuitee.NewAPIClient(configuration)


    t.Run("Test BookApiService Book", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        resp, httpRes, err := apiClient.BookApi.Book().Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

    t.Run("Test BookApiService Prebook", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        resp, httpRes, err := apiClient.BookApi.Prebook().Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

}
