/*
 * Lite API
 * lite api hotel booking api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.nuitee.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for CancelResponse
 */
public class CancelResponseTest {
    private final CancelResponse model = new CancelResponse();

    /**
     * Model tests for CancelResponse
     */
    @Test
    public void testCancelResponse() {
        // TODO: test CancelResponse
    }

    /**
     * Test the property 'bookingId'
     */
    @Test
    public void bookingIdTest() {
        // TODO: test bookingId
    }

    /**
     * Test the property 'cancellationFee'
     */
    @Test
    public void cancellationFeeTest() {
        // TODO: test cancellationFee
    }

    /**
     * Test the property 'currency'
     */
    @Test
    public void currencyTest() {
        // TODO: test currency
    }

    /**
     * Test the property 'refundAmount'
     */
    @Test
    public void refundAmountTest() {
        // TODO: test refundAmount
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

}
