/**
 * Lite API
 * lite api hotel booking api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * https://konfigthis.com
 * Do not edit the class manually.
 */

package com.konfigthis.nuitee.client.model;

import com.konfigthis.nuitee.client.model.PrebookResponseDataRoomTypesInnerRatesInnerCancellationPoliciesCancelPolicyInfosInner;
import java.util.*;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class BookResponseDataCancellationPolicies {
  
  @SerializedName("cancelPolicyInfos")
  private List<PrebookResponseDataRoomTypesInnerRatesInnerCancellationPoliciesCancelPolicyInfosInner> cancelPolicyInfos = null;
  @SerializedName("hotelRemarks")
  private List<String> hotelRemarks = null;
  @SerializedName("refundableTag")
  private String refundableTag = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public List<PrebookResponseDataRoomTypesInnerRatesInnerCancellationPoliciesCancelPolicyInfosInner> getCancelPolicyInfos() {
    return cancelPolicyInfos;
  }
  public void setCancelPolicyInfos(List<PrebookResponseDataRoomTypesInnerRatesInnerCancellationPoliciesCancelPolicyInfosInner> cancelPolicyInfos) {
    this.cancelPolicyInfos = cancelPolicyInfos;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<String> getHotelRemarks() {
    return hotelRemarks;
  }
  public void setHotelRemarks(List<String> hotelRemarks) {
    this.hotelRemarks = hotelRemarks;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getRefundableTag() {
    return refundableTag;
  }
  public void setRefundableTag(String refundableTag) {
    this.refundableTag = refundableTag;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BookResponseDataCancellationPolicies bookResponseDataCancellationPolicies = (BookResponseDataCancellationPolicies) o;
    return (this.cancelPolicyInfos == null ? bookResponseDataCancellationPolicies.cancelPolicyInfos == null : this.cancelPolicyInfos.equals(bookResponseDataCancellationPolicies.cancelPolicyInfos)) &&
        (this.hotelRemarks == null ? bookResponseDataCancellationPolicies.hotelRemarks == null : this.hotelRemarks.equals(bookResponseDataCancellationPolicies.hotelRemarks)) &&
        (this.refundableTag == null ? bookResponseDataCancellationPolicies.refundableTag == null : this.refundableTag.equals(bookResponseDataCancellationPolicies.refundableTag));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.cancelPolicyInfos == null ? 0: this.cancelPolicyInfos.hashCode());
    result = 31 * result + (this.hotelRemarks == null ? 0: this.hotelRemarks.hashCode());
    result = 31 * result + (this.refundableTag == null ? 0: this.refundableTag.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class BookResponseDataCancellationPolicies {\n");
    
    sb.append("  cancelPolicyInfos: ").append(cancelPolicyInfos).append("\n");
    sb.append("  hotelRemarks: ").append(hotelRemarks).append("\n");
    sb.append("  refundableTag: ").append(refundableTag).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
