/**
 * Lite API
 * lite api hotel booking api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * https://konfigthis.com
 * Do not edit the class manually.
 */

package com.konfigthis.nuitee.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class BookResponseDataHotelAddress {
  
  @SerializedName("line1")
  private String line1 = null;
  @SerializedName("line2")
  private String line2 = null;
  @SerializedName("city")
  private String city = null;
  @SerializedName("postalCode")
  private String postalCode = null;
  @SerializedName("region")
  private String region = null;
  @SerializedName("country")
  private String country = null;
  @SerializedName("countryName")
  private String countryName = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getLine1() {
    return line1;
  }
  public void setLine1(String line1) {
    this.line1 = line1;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getLine2() {
    return line2;
  }
  public void setLine2(String line2) {
    this.line2 = line2;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getCity() {
    return city;
  }
  public void setCity(String city) {
    this.city = city;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getPostalCode() {
    return postalCode;
  }
  public void setPostalCode(String postalCode) {
    this.postalCode = postalCode;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getRegion() {
    return region;
  }
  public void setRegion(String region) {
    this.region = region;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getCountry() {
    return country;
  }
  public void setCountry(String country) {
    this.country = country;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getCountryName() {
    return countryName;
  }
  public void setCountryName(String countryName) {
    this.countryName = countryName;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BookResponseDataHotelAddress bookResponseDataHotelAddress = (BookResponseDataHotelAddress) o;
    return (this.line1 == null ? bookResponseDataHotelAddress.line1 == null : this.line1.equals(bookResponseDataHotelAddress.line1)) &&
        (this.line2 == null ? bookResponseDataHotelAddress.line2 == null : this.line2.equals(bookResponseDataHotelAddress.line2)) &&
        (this.city == null ? bookResponseDataHotelAddress.city == null : this.city.equals(bookResponseDataHotelAddress.city)) &&
        (this.postalCode == null ? bookResponseDataHotelAddress.postalCode == null : this.postalCode.equals(bookResponseDataHotelAddress.postalCode)) &&
        (this.region == null ? bookResponseDataHotelAddress.region == null : this.region.equals(bookResponseDataHotelAddress.region)) &&
        (this.country == null ? bookResponseDataHotelAddress.country == null : this.country.equals(bookResponseDataHotelAddress.country)) &&
        (this.countryName == null ? bookResponseDataHotelAddress.countryName == null : this.countryName.equals(bookResponseDataHotelAddress.countryName));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.line1 == null ? 0: this.line1.hashCode());
    result = 31 * result + (this.line2 == null ? 0: this.line2.hashCode());
    result = 31 * result + (this.city == null ? 0: this.city.hashCode());
    result = 31 * result + (this.postalCode == null ? 0: this.postalCode.hashCode());
    result = 31 * result + (this.region == null ? 0: this.region.hashCode());
    result = 31 * result + (this.country == null ? 0: this.country.hashCode());
    result = 31 * result + (this.countryName == null ? 0: this.countryName.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class BookResponseDataHotelAddress {\n");
    
    sb.append("  line1: ").append(line1).append("\n");
    sb.append("  line2: ").append(line2).append("\n");
    sb.append("  city: ").append(city).append("\n");
    sb.append("  postalCode: ").append(postalCode).append("\n");
    sb.append("  region: ").append(region).append("\n");
    sb.append("  country: ").append(country).append("\n");
    sb.append("  countryName: ").append(countryName).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
