/**
 * Lite API
 * lite api hotel booking api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * https://konfigthis.com
 * Do not edit the class manually.
 */

package com.konfigthis.nuitee.client.model;

import com.konfigthis.nuitee.client.model.BookResponseDataBookedRoomsInner;
import com.konfigthis.nuitee.client.model.BookResponseDataCancellation;
import com.konfigthis.nuitee.client.model.BookResponseDataCancellationPolicies;
import com.konfigthis.nuitee.client.model.BookResponseDataGuestInfo;
import com.konfigthis.nuitee.client.model.BookResponseDataHotel;
import java.math.BigDecimal;
import java.util.*;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class BookResponseData {
  
  @SerializedName("bookingId")
  private String bookingId = null;
  @SerializedName("status")
  private String status = null;
  @SerializedName("hotelConfirmationCode")
  private String hotelConfirmationCode = null;
  @SerializedName("checkin")
  private String checkin = null;
  @SerializedName("checkout")
  private String checkout = null;
  @SerializedName("hotel")
  private BookResponseDataHotel hotel = null;
  @SerializedName("bookedRooms")
  private List<BookResponseDataBookedRoomsInner> bookedRooms = null;
  @SerializedName("guestInfo")
  private BookResponseDataGuestInfo guestInfo = null;
  @SerializedName("createdAt")
  private String createdAt = null;
  @SerializedName("cancellation")
  private BookResponseDataCancellation cancellation = null;
  @SerializedName("cancellationPolicies")
  private BookResponseDataCancellationPolicies cancellationPolicies = null;
  @SerializedName("price")
  private BigDecimal price = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getBookingId() {
    return bookingId;
  }
  public void setBookingId(String bookingId) {
    this.bookingId = bookingId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getStatus() {
    return status;
  }
  public void setStatus(String status) {
    this.status = status;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getHotelConfirmationCode() {
    return hotelConfirmationCode;
  }
  public void setHotelConfirmationCode(String hotelConfirmationCode) {
    this.hotelConfirmationCode = hotelConfirmationCode;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getCheckin() {
    return checkin;
  }
  public void setCheckin(String checkin) {
    this.checkin = checkin;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getCheckout() {
    return checkout;
  }
  public void setCheckout(String checkout) {
    this.checkout = checkout;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public BookResponseDataHotel getHotel() {
    return hotel;
  }
  public void setHotel(BookResponseDataHotel hotel) {
    this.hotel = hotel;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<BookResponseDataBookedRoomsInner> getBookedRooms() {
    return bookedRooms;
  }
  public void setBookedRooms(List<BookResponseDataBookedRoomsInner> bookedRooms) {
    this.bookedRooms = bookedRooms;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public BookResponseDataGuestInfo getGuestInfo() {
    return guestInfo;
  }
  public void setGuestInfo(BookResponseDataGuestInfo guestInfo) {
    this.guestInfo = guestInfo;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getCreatedAt() {
    return createdAt;
  }
  public void setCreatedAt(String createdAt) {
    this.createdAt = createdAt;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public BookResponseDataCancellation getCancellation() {
    return cancellation;
  }
  public void setCancellation(BookResponseDataCancellation cancellation) {
    this.cancellation = cancellation;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public BookResponseDataCancellationPolicies getCancellationPolicies() {
    return cancellationPolicies;
  }
  public void setCancellationPolicies(BookResponseDataCancellationPolicies cancellationPolicies) {
    this.cancellationPolicies = cancellationPolicies;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public BigDecimal getPrice() {
    return price;
  }
  public void setPrice(BigDecimal price) {
    this.price = price;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BookResponseData bookResponseData = (BookResponseData) o;
    return (this.bookingId == null ? bookResponseData.bookingId == null : this.bookingId.equals(bookResponseData.bookingId)) &&
        (this.status == null ? bookResponseData.status == null : this.status.equals(bookResponseData.status)) &&
        (this.hotelConfirmationCode == null ? bookResponseData.hotelConfirmationCode == null : this.hotelConfirmationCode.equals(bookResponseData.hotelConfirmationCode)) &&
        (this.checkin == null ? bookResponseData.checkin == null : this.checkin.equals(bookResponseData.checkin)) &&
        (this.checkout == null ? bookResponseData.checkout == null : this.checkout.equals(bookResponseData.checkout)) &&
        (this.hotel == null ? bookResponseData.hotel == null : this.hotel.equals(bookResponseData.hotel)) &&
        (this.bookedRooms == null ? bookResponseData.bookedRooms == null : this.bookedRooms.equals(bookResponseData.bookedRooms)) &&
        (this.guestInfo == null ? bookResponseData.guestInfo == null : this.guestInfo.equals(bookResponseData.guestInfo)) &&
        (this.createdAt == null ? bookResponseData.createdAt == null : this.createdAt.equals(bookResponseData.createdAt)) &&
        (this.cancellation == null ? bookResponseData.cancellation == null : this.cancellation.equals(bookResponseData.cancellation)) &&
        (this.cancellationPolicies == null ? bookResponseData.cancellationPolicies == null : this.cancellationPolicies.equals(bookResponseData.cancellationPolicies)) &&
        (this.price == null ? bookResponseData.price == null : this.price.equals(bookResponseData.price));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.bookingId == null ? 0: this.bookingId.hashCode());
    result = 31 * result + (this.status == null ? 0: this.status.hashCode());
    result = 31 * result + (this.hotelConfirmationCode == null ? 0: this.hotelConfirmationCode.hashCode());
    result = 31 * result + (this.checkin == null ? 0: this.checkin.hashCode());
    result = 31 * result + (this.checkout == null ? 0: this.checkout.hashCode());
    result = 31 * result + (this.hotel == null ? 0: this.hotel.hashCode());
    result = 31 * result + (this.bookedRooms == null ? 0: this.bookedRooms.hashCode());
    result = 31 * result + (this.guestInfo == null ? 0: this.guestInfo.hashCode());
    result = 31 * result + (this.createdAt == null ? 0: this.createdAt.hashCode());
    result = 31 * result + (this.cancellation == null ? 0: this.cancellation.hashCode());
    result = 31 * result + (this.cancellationPolicies == null ? 0: this.cancellationPolicies.hashCode());
    result = 31 * result + (this.price == null ? 0: this.price.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class BookResponseData {\n");
    
    sb.append("  bookingId: ").append(bookingId).append("\n");
    sb.append("  status: ").append(status).append("\n");
    sb.append("  hotelConfirmationCode: ").append(hotelConfirmationCode).append("\n");
    sb.append("  checkin: ").append(checkin).append("\n");
    sb.append("  checkout: ").append(checkout).append("\n");
    sb.append("  hotel: ").append(hotel).append("\n");
    sb.append("  bookedRooms: ").append(bookedRooms).append("\n");
    sb.append("  guestInfo: ").append(guestInfo).append("\n");
    sb.append("  createdAt: ").append(createdAt).append("\n");
    sb.append("  cancellation: ").append(cancellation).append("\n");
    sb.append("  cancellationPolicies: ").append(cancellationPolicies).append("\n");
    sb.append("  price: ").append(price).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
