/**
 * Lite API
 * lite api hotel booking api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * https://konfigthis.com
 * Do not edit the class manually.
 */

package com.konfigthis.nuitee.client.model;

import com.konfigthis.nuitee.client.model.GetHotelRatesResponseDataInnerRoomTypesInnerRatesInnerRetailRateTotalInner;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class BookResponseDataBookedRoomsInnerRateRetailRate {
  
  @SerializedName("total")
  private GetHotelRatesResponseDataInnerRoomTypesInnerRatesInnerRetailRateTotalInner total = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public GetHotelRatesResponseDataInnerRoomTypesInnerRatesInnerRetailRateTotalInner getTotal() {
    return total;
  }
  public void setTotal(GetHotelRatesResponseDataInnerRoomTypesInnerRatesInnerRetailRateTotalInner total) {
    this.total = total;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BookResponseDataBookedRoomsInnerRateRetailRate bookResponseDataBookedRoomsInnerRateRetailRate = (BookResponseDataBookedRoomsInnerRateRetailRate) o;
    return (this.total == null ? bookResponseDataBookedRoomsInnerRateRetailRate.total == null : this.total.equals(bookResponseDataBookedRoomsInnerRateRetailRate.total));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.total == null ? 0: this.total.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class BookResponseDataBookedRoomsInnerRateRetailRate {\n");
    
    sb.append("  total: ").append(total).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
