/**
 * Lite API
 * lite api hotel booking api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * https://konfigthis.com
 * Do not edit the class manually.
 */

package com.konfigthis.nuitee.client.model;

import java.math.BigDecimal;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class CancelResponse {
  
  @SerializedName("bookingId")
  private String bookingId = null;
  @SerializedName("cancellation_fee")
  private Integer cancellationFee = null;
  @SerializedName("currency")
  private String currency = null;
  @SerializedName("refund_amount")
  private BigDecimal refundAmount = null;
  @SerializedName("status")
  private String status = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getBookingId() {
    return bookingId;
  }
  public void setBookingId(String bookingId) {
    this.bookingId = bookingId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getCancellationFee() {
    return cancellationFee;
  }
  public void setCancellationFee(Integer cancellationFee) {
    this.cancellationFee = cancellationFee;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getCurrency() {
    return currency;
  }
  public void setCurrency(String currency) {
    this.currency = currency;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public BigDecimal getRefundAmount() {
    return refundAmount;
  }
  public void setRefundAmount(BigDecimal refundAmount) {
    this.refundAmount = refundAmount;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getStatus() {
    return status;
  }
  public void setStatus(String status) {
    this.status = status;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CancelResponse cancelResponse = (CancelResponse) o;
    return (this.bookingId == null ? cancelResponse.bookingId == null : this.bookingId.equals(cancelResponse.bookingId)) &&
        (this.cancellationFee == null ? cancelResponse.cancellationFee == null : this.cancellationFee.equals(cancelResponse.cancellationFee)) &&
        (this.currency == null ? cancelResponse.currency == null : this.currency.equals(cancelResponse.currency)) &&
        (this.refundAmount == null ? cancelResponse.refundAmount == null : this.refundAmount.equals(cancelResponse.refundAmount)) &&
        (this.status == null ? cancelResponse.status == null : this.status.equals(cancelResponse.status));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.bookingId == null ? 0: this.bookingId.hashCode());
    result = 31 * result + (this.cancellationFee == null ? 0: this.cancellationFee.hashCode());
    result = 31 * result + (this.currency == null ? 0: this.currency.hashCode());
    result = 31 * result + (this.refundAmount == null ? 0: this.refundAmount.hashCode());
    result = 31 * result + (this.status == null ? 0: this.status.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class CancelResponse {\n");
    
    sb.append("  bookingId: ").append(bookingId).append("\n");
    sb.append("  cancellationFee: ").append(cancellationFee).append("\n");
    sb.append("  currency: ").append(currency).append("\n");
    sb.append("  refundAmount: ").append(refundAmount).append("\n");
    sb.append("  status: ").append(status).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
