/**
 * Lite API
 * lite api hotel booking api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * https://konfigthis.com
 * Do not edit the class manually.
 */

package com.konfigthis.nuitee.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class ListBookingsResponseDataInner {
  
  @SerializedName("bookingId")
  private String bookingId = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getBookingId() {
    return bookingId;
  }
  public void setBookingId(String bookingId) {
    this.bookingId = bookingId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ListBookingsResponseDataInner listBookingsResponseDataInner = (ListBookingsResponseDataInner) o;
    return (this.bookingId == null ? listBookingsResponseDataInner.bookingId == null : this.bookingId.equals(listBookingsResponseDataInner.bookingId));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.bookingId == null ? 0: this.bookingId.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class ListBookingsResponseDataInner {\n");
    
    sb.append("  bookingId: ").append(bookingId).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
