/**
 * Lite API
 * lite api hotel booking api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * https://konfigthis.com
 * Do not edit the class manually.
 */

package com.konfigthis.nuitee.client.model;

import java.math.BigDecimal;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class ListHotelsResponseDataInner {
  
  @SerializedName("id")
  private Integer id = null;
  @SerializedName("name")
  private String name = null;
  @SerializedName("hotelDescription")
  private String hotelDescription = null;
  @SerializedName("hotelImportantInformation")
  private String hotelImportantInformation = null;
  @SerializedName("currency")
  private String currency = null;
  @SerializedName("country")
  private String country = null;
  @SerializedName("city")
  private String city = null;
  @SerializedName("latitude")
  private BigDecimal latitude = null;
  @SerializedName("longitude")
  private BigDecimal longitude = null;
  @SerializedName("address")
  private String address = null;
  @SerializedName("zip")
  private String zip = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getId() {
    return id;
  }
  public void setId(Integer id) {
    this.id = id;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getHotelDescription() {
    return hotelDescription;
  }
  public void setHotelDescription(String hotelDescription) {
    this.hotelDescription = hotelDescription;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getHotelImportantInformation() {
    return hotelImportantInformation;
  }
  public void setHotelImportantInformation(String hotelImportantInformation) {
    this.hotelImportantInformation = hotelImportantInformation;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getCurrency() {
    return currency;
  }
  public void setCurrency(String currency) {
    this.currency = currency;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getCountry() {
    return country;
  }
  public void setCountry(String country) {
    this.country = country;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getCity() {
    return city;
  }
  public void setCity(String city) {
    this.city = city;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public BigDecimal getLatitude() {
    return latitude;
  }
  public void setLatitude(BigDecimal latitude) {
    this.latitude = latitude;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public BigDecimal getLongitude() {
    return longitude;
  }
  public void setLongitude(BigDecimal longitude) {
    this.longitude = longitude;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getAddress() {
    return address;
  }
  public void setAddress(String address) {
    this.address = address;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getZip() {
    return zip;
  }
  public void setZip(String zip) {
    this.zip = zip;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ListHotelsResponseDataInner listHotelsResponseDataInner = (ListHotelsResponseDataInner) o;
    return (this.id == null ? listHotelsResponseDataInner.id == null : this.id.equals(listHotelsResponseDataInner.id)) &&
        (this.name == null ? listHotelsResponseDataInner.name == null : this.name.equals(listHotelsResponseDataInner.name)) &&
        (this.hotelDescription == null ? listHotelsResponseDataInner.hotelDescription == null : this.hotelDescription.equals(listHotelsResponseDataInner.hotelDescription)) &&
        (this.hotelImportantInformation == null ? listHotelsResponseDataInner.hotelImportantInformation == null : this.hotelImportantInformation.equals(listHotelsResponseDataInner.hotelImportantInformation)) &&
        (this.currency == null ? listHotelsResponseDataInner.currency == null : this.currency.equals(listHotelsResponseDataInner.currency)) &&
        (this.country == null ? listHotelsResponseDataInner.country == null : this.country.equals(listHotelsResponseDataInner.country)) &&
        (this.city == null ? listHotelsResponseDataInner.city == null : this.city.equals(listHotelsResponseDataInner.city)) &&
        (this.latitude == null ? listHotelsResponseDataInner.latitude == null : this.latitude.equals(listHotelsResponseDataInner.latitude)) &&
        (this.longitude == null ? listHotelsResponseDataInner.longitude == null : this.longitude.equals(listHotelsResponseDataInner.longitude)) &&
        (this.address == null ? listHotelsResponseDataInner.address == null : this.address.equals(listHotelsResponseDataInner.address)) &&
        (this.zip == null ? listHotelsResponseDataInner.zip == null : this.zip.equals(listHotelsResponseDataInner.zip));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.id == null ? 0: this.id.hashCode());
    result = 31 * result + (this.name == null ? 0: this.name.hashCode());
    result = 31 * result + (this.hotelDescription == null ? 0: this.hotelDescription.hashCode());
    result = 31 * result + (this.hotelImportantInformation == null ? 0: this.hotelImportantInformation.hashCode());
    result = 31 * result + (this.currency == null ? 0: this.currency.hashCode());
    result = 31 * result + (this.country == null ? 0: this.country.hashCode());
    result = 31 * result + (this.city == null ? 0: this.city.hashCode());
    result = 31 * result + (this.latitude == null ? 0: this.latitude.hashCode());
    result = 31 * result + (this.longitude == null ? 0: this.longitude.hashCode());
    result = 31 * result + (this.address == null ? 0: this.address.hashCode());
    result = 31 * result + (this.zip == null ? 0: this.zip.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class ListHotelsResponseDataInner {\n");
    
    sb.append("  id: ").append(id).append("\n");
    sb.append("  name: ").append(name).append("\n");
    sb.append("  hotelDescription: ").append(hotelDescription).append("\n");
    sb.append("  hotelImportantInformation: ").append(hotelImportantInformation).append("\n");
    sb.append("  currency: ").append(currency).append("\n");
    sb.append("  country: ").append(country).append("\n");
    sb.append("  city: ").append(city).append("\n");
    sb.append("  latitude: ").append(latitude).append("\n");
    sb.append("  longitude: ").append(longitude).append("\n");
    sb.append("  address: ").append(address).append("\n");
    sb.append("  zip: ").append(zip).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
