/**
 * Lite API
 * lite api hotel booking api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * https://konfigthis.com
 * Do not edit the class manually.
 */

package com.konfigthis.nuitee.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class PrebookRequest {
  
  @SerializedName("sessionId")
  private String sessionId = null;
  @SerializedName("rateId")
  private String rateId = null;

  /**
   * session id retrievied from rates response
   **/
  @ApiModelProperty(value = "session id retrievied from rates response")
  public String getSessionId() {
    return sessionId;
  }
  public void setSessionId(String sessionId) {
    this.sessionId = sessionId;
  }

  /**
   * rate id retrieved from rates response
   **/
  @ApiModelProperty(required = true, value = "rate id retrieved from rates response")
  public String getRateId() {
    return rateId;
  }
  public void setRateId(String rateId) {
    this.rateId = rateId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PrebookRequest prebookRequest = (PrebookRequest) o;
    return (this.sessionId == null ? prebookRequest.sessionId == null : this.sessionId.equals(prebookRequest.sessionId)) &&
        (this.rateId == null ? prebookRequest.rateId == null : this.rateId.equals(prebookRequest.rateId));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.sessionId == null ? 0: this.sessionId.hashCode());
    result = 31 * result + (this.rateId == null ? 0: this.rateId.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class PrebookRequest {\n");
    
    sb.append("  sessionId: ").append(sessionId).append("\n");
    sb.append("  rateId: ").append(rateId).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
