/**
 * Lite API
 * lite api hotel booking api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * https://konfigthis.com
 * Do not edit the class manually.
 */

package com.konfigthis.nuitee.client.model;

import com.konfigthis.nuitee.client.model.PrebookResponseData;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class PrebookResponse {
  
  @SerializedName("data")
  private PrebookResponseData data = null;
  @SerializedName("guestLevel")
  private Integer guestLevel = null;
  @SerializedName("sandbox")
  private Boolean sandbox = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public PrebookResponseData getData() {
    return data;
  }
  public void setData(PrebookResponseData data) {
    this.data = data;
  }

  /**
   * guests loyalty level granting them discounts and benefit
   **/
  @ApiModelProperty(value = "guests loyalty level granting them discounts and benefit")
  public Integer getGuestLevel() {
    return guestLevel;
  }
  public void setGuestLevel(Integer guestLevel) {
    this.guestLevel = guestLevel;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Boolean getSandbox() {
    return sandbox;
  }
  public void setSandbox(Boolean sandbox) {
    this.sandbox = sandbox;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PrebookResponse prebookResponse = (PrebookResponse) o;
    return (this.data == null ? prebookResponse.data == null : this.data.equals(prebookResponse.data)) &&
        (this.guestLevel == null ? prebookResponse.guestLevel == null : this.guestLevel.equals(prebookResponse.guestLevel)) &&
        (this.sandbox == null ? prebookResponse.sandbox == null : this.sandbox.equals(prebookResponse.sandbox));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.data == null ? 0: this.data.hashCode());
    result = 31 * result + (this.guestLevel == null ? 0: this.guestLevel.hashCode());
    result = 31 * result + (this.sandbox == null ? 0: this.sandbox.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class PrebookResponse {\n");
    
    sb.append("  data: ").append(data).append("\n");
    sb.append("  guestLevel: ").append(guestLevel).append("\n");
    sb.append("  sandbox: ").append(sandbox).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
