/**
 * Lite API
 * lite api hotel booking api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * https://konfigthis.com
 * Do not edit the class manually.
 */

package com.konfigthis.nuitee.client.model;

import com.konfigthis.nuitee.client.model.BookResponseDataBookedRoomsInnerRateRetailRate;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class RetrieveResponseDataBookedRoomsInnerRate {
  
  @SerializedName("maxOccupancy")
  private Integer maxOccupancy = null;
  @SerializedName("retailRate")
  private BookResponseDataBookedRoomsInnerRateRetailRate retailRate = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getMaxOccupancy() {
    return maxOccupancy;
  }
  public void setMaxOccupancy(Integer maxOccupancy) {
    this.maxOccupancy = maxOccupancy;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public BookResponseDataBookedRoomsInnerRateRetailRate getRetailRate() {
    return retailRate;
  }
  public void setRetailRate(BookResponseDataBookedRoomsInnerRateRetailRate retailRate) {
    this.retailRate = retailRate;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RetrieveResponseDataBookedRoomsInnerRate retrieveResponseDataBookedRoomsInnerRate = (RetrieveResponseDataBookedRoomsInnerRate) o;
    return (this.maxOccupancy == null ? retrieveResponseDataBookedRoomsInnerRate.maxOccupancy == null : this.maxOccupancy.equals(retrieveResponseDataBookedRoomsInnerRate.maxOccupancy)) &&
        (this.retailRate == null ? retrieveResponseDataBookedRoomsInnerRate.retailRate == null : this.retailRate.equals(retrieveResponseDataBookedRoomsInnerRate.retailRate));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.maxOccupancy == null ? 0: this.maxOccupancy.hashCode());
    result = 31 * result + (this.retailRate == null ? 0: this.retailRate.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class RetrieveResponseDataBookedRoomsInnerRate {\n");
    
    sb.append("  maxOccupancy: ").append(maxOccupancy).append("\n");
    sb.append("  retailRate: ").append(retailRate).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
