<?php

/**
 * BookingManagementApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  Nuitee
 * @author   Konfig
 * @link     https://konfigthis.com
 */

/**
 * Lite API
 *
 * lite api hotel booking api
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://konfigthis.com
 */


namespace Nuitee\Test\Api;

use \Nuitee\Configuration;
use \Nuitee\ApiException;
use \Nuitee\ObjectSerializer;
use PHPUnit\Framework\TestCase;

class BookingManagementApiTest extends TestCase
{

    protected \Nuitee\Api\BookingManagementApi $api;

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
        $apiKey = getenv("NUITEE_API_KEY");
        $config = \Nuitee\Configuration::getDefaultConfiguration()->setApiKey('X-API-Key', $apiKey);
        $this->api = new \Nuitee\Api\BookingManagementApi($config);
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for cancel
     *
     * Booking cancel.
     *
     */
    public function testCancel()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listBookings
     *
     * Booking list.
     *
     */
    public function testListBookings()
    {
        $response = $this->api->listBookings("FrT56hfty");
        $this->assertNotNull(
            $response,
            "response is null"
        );
    }

    /**
     * Test case for retrieve
     *
     * Booking retrieve.
     *
     */
    public function testRetrieve()
    {
        $response = $this->api->retrieve("3uFbXs3Vz");
        $this->assertNotNull(
            $response,
            "response is null"
        );
    }
}
