<?php
/**
 * PrebookResponseDataRoomTypesInnerTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Nuitee
 * @author   Konfig
 * @link     https://konfigthis.com
 */

/**
 * Lite API
 *
 * lite api hotel booking api
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://konfigthis.com
 */


namespace Nuitee\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * PrebookResponseDataRoomTypesInnerTest Class Doc Comment
 *
 * @category    Class
 * @description PrebookResponseDataRoomTypesInner
 * @package     Nuitee
 */
class PrebookResponseDataRoomTypesInnerTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "PrebookResponseDataRoomTypesInner"
     */
    public function testPrebookResponseDataRoomTypesInner()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "max_occupancy"
     */
    public function testPropertyMaxOccupancy()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "rates"
     */
    public function testPropertyRates()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
