/*
Lite API

lite api hotel booking api

API version: 1.0.0
*/

// Code generated by Konfig (https://konfigthis.com); DO NOT EDIT.

package nuitee

import (
	"encoding/json"
)

// PrebookResponseDataRoomTypesInnerRatesInnerCancellationPoliciesCancelPolicyInfosInner struct for PrebookResponseDataRoomTypesInnerRatesInnerCancellationPoliciesCancelPolicyInfosInner
type PrebookResponseDataRoomTypesInnerRatesInnerCancellationPoliciesCancelPolicyInfosInner struct {
	CancelTime *string `json:"cancelTime,omitempty"`
	Amount *float32 `json:"amount,omitempty"`
	Type *string `json:"type,omitempty"`
}

// NewPrebookResponseDataRoomTypesInnerRatesInnerCancellationPoliciesCancelPolicyInfosInner instantiates a new PrebookResponseDataRoomTypesInnerRatesInnerCancellationPoliciesCancelPolicyInfosInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPrebookResponseDataRoomTypesInnerRatesInnerCancellationPoliciesCancelPolicyInfosInner() *PrebookResponseDataRoomTypesInnerRatesInnerCancellationPoliciesCancelPolicyInfosInner {
	this := PrebookResponseDataRoomTypesInnerRatesInnerCancellationPoliciesCancelPolicyInfosInner{}
	return &this
}

// NewPrebookResponseDataRoomTypesInnerRatesInnerCancellationPoliciesCancelPolicyInfosInnerWithDefaults instantiates a new PrebookResponseDataRoomTypesInnerRatesInnerCancellationPoliciesCancelPolicyInfosInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPrebookResponseDataRoomTypesInnerRatesInnerCancellationPoliciesCancelPolicyInfosInnerWithDefaults() *PrebookResponseDataRoomTypesInnerRatesInnerCancellationPoliciesCancelPolicyInfosInner {
	this := PrebookResponseDataRoomTypesInnerRatesInnerCancellationPoliciesCancelPolicyInfosInner{}
	return &this
}

// GetCancelTime returns the CancelTime field value if set, zero value otherwise.
func (o *PrebookResponseDataRoomTypesInnerRatesInnerCancellationPoliciesCancelPolicyInfosInner) GetCancelTime() string {
	if o == nil || isNil(o.CancelTime) {
		var ret string
		return ret
	}
	return *o.CancelTime
}

// GetCancelTimeOk returns a tuple with the CancelTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PrebookResponseDataRoomTypesInnerRatesInnerCancellationPoliciesCancelPolicyInfosInner) GetCancelTimeOk() (*string, bool) {
	if o == nil || isNil(o.CancelTime) {
    return nil, false
	}
	return o.CancelTime, true
}

// HasCancelTime returns a boolean if a field has been set.
func (o *PrebookResponseDataRoomTypesInnerRatesInnerCancellationPoliciesCancelPolicyInfosInner) HasCancelTime() bool {
	if o != nil && !isNil(o.CancelTime) {
		return true
	}

	return false
}

// SetCancelTime gets a reference to the given string and assigns it to the CancelTime field.
func (o *PrebookResponseDataRoomTypesInnerRatesInnerCancellationPoliciesCancelPolicyInfosInner) SetCancelTime(v string) {
	o.CancelTime = &v
}

// GetAmount returns the Amount field value if set, zero value otherwise.
func (o *PrebookResponseDataRoomTypesInnerRatesInnerCancellationPoliciesCancelPolicyInfosInner) GetAmount() float32 {
	if o == nil || isNil(o.Amount) {
		var ret float32
		return ret
	}
	return *o.Amount
}

// GetAmountOk returns a tuple with the Amount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PrebookResponseDataRoomTypesInnerRatesInnerCancellationPoliciesCancelPolicyInfosInner) GetAmountOk() (*float32, bool) {
	if o == nil || isNil(o.Amount) {
    return nil, false
	}
	return o.Amount, true
}

// HasAmount returns a boolean if a field has been set.
func (o *PrebookResponseDataRoomTypesInnerRatesInnerCancellationPoliciesCancelPolicyInfosInner) HasAmount() bool {
	if o != nil && !isNil(o.Amount) {
		return true
	}

	return false
}

// SetAmount gets a reference to the given float32 and assigns it to the Amount field.
func (o *PrebookResponseDataRoomTypesInnerRatesInnerCancellationPoliciesCancelPolicyInfosInner) SetAmount(v float32) {
	o.Amount = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *PrebookResponseDataRoomTypesInnerRatesInnerCancellationPoliciesCancelPolicyInfosInner) GetType() string {
	if o == nil || isNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PrebookResponseDataRoomTypesInnerRatesInnerCancellationPoliciesCancelPolicyInfosInner) GetTypeOk() (*string, bool) {
	if o == nil || isNil(o.Type) {
    return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *PrebookResponseDataRoomTypesInnerRatesInnerCancellationPoliciesCancelPolicyInfosInner) HasType() bool {
	if o != nil && !isNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *PrebookResponseDataRoomTypesInnerRatesInnerCancellationPoliciesCancelPolicyInfosInner) SetType(v string) {
	o.Type = &v
}

func (o PrebookResponseDataRoomTypesInnerRatesInnerCancellationPoliciesCancelPolicyInfosInner) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.CancelTime) {
		toSerialize["cancelTime"] = o.CancelTime
	}
	if !isNil(o.Amount) {
		toSerialize["amount"] = o.Amount
	}
	if !isNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	return json.Marshal(toSerialize)
}

type NullablePrebookResponseDataRoomTypesInnerRatesInnerCancellationPoliciesCancelPolicyInfosInner struct {
	value *PrebookResponseDataRoomTypesInnerRatesInnerCancellationPoliciesCancelPolicyInfosInner
	isSet bool
}

func (v NullablePrebookResponseDataRoomTypesInnerRatesInnerCancellationPoliciesCancelPolicyInfosInner) Get() *PrebookResponseDataRoomTypesInnerRatesInnerCancellationPoliciesCancelPolicyInfosInner {
	return v.value
}

func (v *NullablePrebookResponseDataRoomTypesInnerRatesInnerCancellationPoliciesCancelPolicyInfosInner) Set(val *PrebookResponseDataRoomTypesInnerRatesInnerCancellationPoliciesCancelPolicyInfosInner) {
	v.value = val
	v.isSet = true
}

func (v NullablePrebookResponseDataRoomTypesInnerRatesInnerCancellationPoliciesCancelPolicyInfosInner) IsSet() bool {
	return v.isSet
}

func (v *NullablePrebookResponseDataRoomTypesInnerRatesInnerCancellationPoliciesCancelPolicyInfosInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePrebookResponseDataRoomTypesInnerRatesInnerCancellationPoliciesCancelPolicyInfosInner(val *PrebookResponseDataRoomTypesInnerRatesInnerCancellationPoliciesCancelPolicyInfosInner) *NullablePrebookResponseDataRoomTypesInnerRatesInnerCancellationPoliciesCancelPolicyInfosInner {
	return &NullablePrebookResponseDataRoomTypesInnerRatesInnerCancellationPoliciesCancelPolicyInfosInner{value: val, isSet: true}
}

func (v NullablePrebookResponseDataRoomTypesInnerRatesInnerCancellationPoliciesCancelPolicyInfosInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePrebookResponseDataRoomTypesInnerRatesInnerCancellationPoliciesCancelPolicyInfosInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


