/*
Lite API

lite api hotel booking api

API version: 1.0.0
*/

// Code generated by Konfig (https://konfigthis.com); DO NOT EDIT.

package nuitee

import (
	"encoding/json"
)

// GetHotelRatesResponseDataInnerRoomTypesInnerRatesInnerRetailRate struct for GetHotelRatesResponseDataInnerRoomTypesInnerRatesInnerRetailRate
type GetHotelRatesResponseDataInnerRoomTypesInnerRatesInnerRetailRate struct {
	Total []GetHotelRatesResponseDataInnerRoomTypesInnerRatesInnerRetailRateTotalInner `json:"total,omitempty"`
	TaxesAndFees []GetHotelRatesResponseDataInnerRoomTypesInnerRatesInnerRetailRateTaxesAndFeesInner `json:"taxesAndFees,omitempty"`
}

// NewGetHotelRatesResponseDataInnerRoomTypesInnerRatesInnerRetailRate instantiates a new GetHotelRatesResponseDataInnerRoomTypesInnerRatesInnerRetailRate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetHotelRatesResponseDataInnerRoomTypesInnerRatesInnerRetailRate() *GetHotelRatesResponseDataInnerRoomTypesInnerRatesInnerRetailRate {
	this := GetHotelRatesResponseDataInnerRoomTypesInnerRatesInnerRetailRate{}
	return &this
}

// NewGetHotelRatesResponseDataInnerRoomTypesInnerRatesInnerRetailRateWithDefaults instantiates a new GetHotelRatesResponseDataInnerRoomTypesInnerRatesInnerRetailRate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetHotelRatesResponseDataInnerRoomTypesInnerRatesInnerRetailRateWithDefaults() *GetHotelRatesResponseDataInnerRoomTypesInnerRatesInnerRetailRate {
	this := GetHotelRatesResponseDataInnerRoomTypesInnerRatesInnerRetailRate{}
	return &this
}

// GetTotal returns the Total field value if set, zero value otherwise.
func (o *GetHotelRatesResponseDataInnerRoomTypesInnerRatesInnerRetailRate) GetTotal() []GetHotelRatesResponseDataInnerRoomTypesInnerRatesInnerRetailRateTotalInner {
	if o == nil || isNil(o.Total) {
		var ret []GetHotelRatesResponseDataInnerRoomTypesInnerRatesInnerRetailRateTotalInner
		return ret
	}
	return o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetHotelRatesResponseDataInnerRoomTypesInnerRatesInnerRetailRate) GetTotalOk() ([]GetHotelRatesResponseDataInnerRoomTypesInnerRatesInnerRetailRateTotalInner, bool) {
	if o == nil || isNil(o.Total) {
    return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *GetHotelRatesResponseDataInnerRoomTypesInnerRatesInnerRetailRate) HasTotal() bool {
	if o != nil && !isNil(o.Total) {
		return true
	}

	return false
}

// SetTotal gets a reference to the given []GetHotelRatesResponseDataInnerRoomTypesInnerRatesInnerRetailRateTotalInner and assigns it to the Total field.
func (o *GetHotelRatesResponseDataInnerRoomTypesInnerRatesInnerRetailRate) SetTotal(v []GetHotelRatesResponseDataInnerRoomTypesInnerRatesInnerRetailRateTotalInner) {
	o.Total = v
}

// GetTaxesAndFees returns the TaxesAndFees field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetHotelRatesResponseDataInnerRoomTypesInnerRatesInnerRetailRate) GetTaxesAndFees() []GetHotelRatesResponseDataInnerRoomTypesInnerRatesInnerRetailRateTaxesAndFeesInner {
	if o == nil {
		var ret []GetHotelRatesResponseDataInnerRoomTypesInnerRatesInnerRetailRateTaxesAndFeesInner
		return ret
	}
	return o.TaxesAndFees
}

// GetTaxesAndFeesOk returns a tuple with the TaxesAndFees field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetHotelRatesResponseDataInnerRoomTypesInnerRatesInnerRetailRate) GetTaxesAndFeesOk() ([]GetHotelRatesResponseDataInnerRoomTypesInnerRatesInnerRetailRateTaxesAndFeesInner, bool) {
	if o == nil || isNil(o.TaxesAndFees) {
    return nil, false
	}
	return o.TaxesAndFees, true
}

// HasTaxesAndFees returns a boolean if a field has been set.
func (o *GetHotelRatesResponseDataInnerRoomTypesInnerRatesInnerRetailRate) HasTaxesAndFees() bool {
	if o != nil && isNil(o.TaxesAndFees) {
		return true
	}

	return false
}

// SetTaxesAndFees gets a reference to the given []GetHotelRatesResponseDataInnerRoomTypesInnerRatesInnerRetailRateTaxesAndFeesInner and assigns it to the TaxesAndFees field.
func (o *GetHotelRatesResponseDataInnerRoomTypesInnerRatesInnerRetailRate) SetTaxesAndFees(v []GetHotelRatesResponseDataInnerRoomTypesInnerRatesInnerRetailRateTaxesAndFeesInner) {
	o.TaxesAndFees = v
}

func (o GetHotelRatesResponseDataInnerRoomTypesInnerRatesInnerRetailRate) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Total) {
		toSerialize["total"] = o.Total
	}
	if o.TaxesAndFees != nil {
		toSerialize["taxesAndFees"] = o.TaxesAndFees
	}
	return json.Marshal(toSerialize)
}

type NullableGetHotelRatesResponseDataInnerRoomTypesInnerRatesInnerRetailRate struct {
	value *GetHotelRatesResponseDataInnerRoomTypesInnerRatesInnerRetailRate
	isSet bool
}

func (v NullableGetHotelRatesResponseDataInnerRoomTypesInnerRatesInnerRetailRate) Get() *GetHotelRatesResponseDataInnerRoomTypesInnerRatesInnerRetailRate {
	return v.value
}

func (v *NullableGetHotelRatesResponseDataInnerRoomTypesInnerRatesInnerRetailRate) Set(val *GetHotelRatesResponseDataInnerRoomTypesInnerRatesInnerRetailRate) {
	v.value = val
	v.isSet = true
}

func (v NullableGetHotelRatesResponseDataInnerRoomTypesInnerRatesInnerRetailRate) IsSet() bool {
	return v.isSet
}

func (v *NullableGetHotelRatesResponseDataInnerRoomTypesInnerRatesInnerRetailRate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetHotelRatesResponseDataInnerRoomTypesInnerRatesInnerRetailRate(val *GetHotelRatesResponseDataInnerRoomTypesInnerRatesInnerRetailRate) *NullableGetHotelRatesResponseDataInnerRoomTypesInnerRatesInnerRetailRate {
	return &NullableGetHotelRatesResponseDataInnerRoomTypesInnerRatesInnerRetailRate{value: val, isSet: true}
}

func (v NullableGetHotelRatesResponseDataInnerRoomTypesInnerRatesInnerRetailRate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetHotelRatesResponseDataInnerRoomTypesInnerRatesInnerRetailRate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


