/*
Lite API

lite api hotel booking api

API version: 1.0.0
*/

// Code generated by Konfig (https://konfigthis.com); DO NOT EDIT.

package nuitee

import (
	"encoding/json"
)

// Retrieve400ResponseError struct for Retrieve400ResponseError
type Retrieve400ResponseError struct {
	Code *float32 `json:"code,omitempty"`
	Message *string `json:"message,omitempty"`
}

// NewRetrieve400ResponseError instantiates a new Retrieve400ResponseError object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRetrieve400ResponseError() *Retrieve400ResponseError {
	this := Retrieve400ResponseError{}
	return &this
}

// NewRetrieve400ResponseErrorWithDefaults instantiates a new Retrieve400ResponseError object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRetrieve400ResponseErrorWithDefaults() *Retrieve400ResponseError {
	this := Retrieve400ResponseError{}
	return &this
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *Retrieve400ResponseError) GetCode() float32 {
	if o == nil || isNil(o.Code) {
		var ret float32
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Retrieve400ResponseError) GetCodeOk() (*float32, bool) {
	if o == nil || isNil(o.Code) {
    return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *Retrieve400ResponseError) HasCode() bool {
	if o != nil && !isNil(o.Code) {
		return true
	}

	return false
}

// SetCode gets a reference to the given float32 and assigns it to the Code field.
func (o *Retrieve400ResponseError) SetCode(v float32) {
	o.Code = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *Retrieve400ResponseError) GetMessage() string {
	if o == nil || isNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Retrieve400ResponseError) GetMessageOk() (*string, bool) {
	if o == nil || isNil(o.Message) {
    return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *Retrieve400ResponseError) HasMessage() bool {
	if o != nil && !isNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *Retrieve400ResponseError) SetMessage(v string) {
	o.Message = &v
}

func (o Retrieve400ResponseError) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Code) {
		toSerialize["code"] = o.Code
	}
	if !isNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	return json.Marshal(toSerialize)
}

type NullableRetrieve400ResponseError struct {
	value *Retrieve400ResponseError
	isSet bool
}

func (v NullableRetrieve400ResponseError) Get() *Retrieve400ResponseError {
	return v.value
}

func (v *NullableRetrieve400ResponseError) Set(val *Retrieve400ResponseError) {
	v.value = val
	v.isSet = true
}

func (v NullableRetrieve400ResponseError) IsSet() bool {
	return v.isSet
}

func (v *NullableRetrieve400ResponseError) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRetrieve400ResponseError(val *Retrieve400ResponseError) *NullableRetrieve400ResponseError {
	return &NullableRetrieve400ResponseError{value: val, isSet: true}
}

func (v NullableRetrieve400ResponseError) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRetrieve400ResponseError) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


