/*
Lite API

lite api hotel booking api

API version: 1.0.0
*/

// Code generated by Konfig (https://konfigthis.com); DO NOT EDIT.

package nuitee

import (
	"encoding/json"
)

// GetHotels400Response struct for GetHotels400Response
type GetHotels400Response struct {
	Error *GetHotels400ResponseError `json:"error,omitempty"`
}

// NewGetHotels400Response instantiates a new GetHotels400Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetHotels400Response() *GetHotels400Response {
	this := GetHotels400Response{}
	return &this
}

// NewGetHotels400ResponseWithDefaults instantiates a new GetHotels400Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetHotels400ResponseWithDefaults() *GetHotels400Response {
	this := GetHotels400Response{}
	return &this
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *GetHotels400Response) GetError() GetHotels400ResponseError {
	if o == nil || isNil(o.Error) {
		var ret GetHotels400ResponseError
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetHotels400Response) GetErrorOk() (*GetHotels400ResponseError, bool) {
	if o == nil || isNil(o.Error) {
    return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *GetHotels400Response) HasError() bool {
	if o != nil && !isNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given GetHotels400ResponseError and assigns it to the Error field.
func (o *GetHotels400Response) SetError(v GetHotels400ResponseError) {
	o.Error = &v
}

func (o GetHotels400Response) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	return json.Marshal(toSerialize)
}

type NullableGetHotels400Response struct {
	value *GetHotels400Response
	isSet bool
}

func (v NullableGetHotels400Response) Get() *GetHotels400Response {
	return v.value
}

func (v *NullableGetHotels400Response) Set(val *GetHotels400Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetHotels400Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetHotels400Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetHotels400Response(val *GetHotels400Response) *NullableGetHotels400Response {
	return &NullableGetHotels400Response{value: val, isSet: true}
}

func (v NullableGetHotels400Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetHotels400Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


