/*
Lite API

lite api hotel booking api

API version: 1.0.0
*/

// Code generated by Konfig (https://konfigthis.com); DO NOT EDIT.

package nuitee

import (
	"encoding/json"
)

// PrebookRequest struct for PrebookRequest
type PrebookRequest struct {
	// session id retrievied from rates response
	SessionId *string `json:"sessionId,omitempty"`
	// rate id retrieved from rates response
	RateId string `json:"rateId"`
}

// NewPrebookRequest instantiates a new PrebookRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPrebookRequest(rateId string) *PrebookRequest {
	this := PrebookRequest{}
	this.RateId = rateId
	return &this
}

// NewPrebookRequestWithDefaults instantiates a new PrebookRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPrebookRequestWithDefaults() *PrebookRequest {
	this := PrebookRequest{}
	return &this
}

// GetSessionId returns the SessionId field value if set, zero value otherwise.
func (o *PrebookRequest) GetSessionId() string {
	if o == nil || isNil(o.SessionId) {
		var ret string
		return ret
	}
	return *o.SessionId
}

// GetSessionIdOk returns a tuple with the SessionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PrebookRequest) GetSessionIdOk() (*string, bool) {
	if o == nil || isNil(o.SessionId) {
    return nil, false
	}
	return o.SessionId, true
}

// HasSessionId returns a boolean if a field has been set.
func (o *PrebookRequest) HasSessionId() bool {
	if o != nil && !isNil(o.SessionId) {
		return true
	}

	return false
}

// SetSessionId gets a reference to the given string and assigns it to the SessionId field.
func (o *PrebookRequest) SetSessionId(v string) {
	o.SessionId = &v
}

// GetRateId returns the RateId field value
func (o *PrebookRequest) GetRateId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RateId
}

// GetRateIdOk returns a tuple with the RateId field value
// and a boolean to check if the value has been set.
func (o *PrebookRequest) GetRateIdOk() (*string, bool) {
	if o == nil {
    return nil, false
	}
	return &o.RateId, true
}

// SetRateId sets field value
func (o *PrebookRequest) SetRateId(v string) {
	o.RateId = v
}

func (o PrebookRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.SessionId) {
		toSerialize["sessionId"] = o.SessionId
	}
	if true {
		toSerialize["rateId"] = o.RateId
	}
	return json.Marshal(toSerialize)
}

type NullablePrebookRequest struct {
	value *PrebookRequest
	isSet bool
}

func (v NullablePrebookRequest) Get() *PrebookRequest {
	return v.value
}

func (v *NullablePrebookRequest) Set(val *PrebookRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePrebookRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePrebookRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePrebookRequest(val *PrebookRequest) *NullablePrebookRequest {
	return &NullablePrebookRequest{value: val, isSet: true}
}

func (v NullablePrebookRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePrebookRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


