/*
Lite API

lite api hotel booking api

API version: 1.0.0
*/

// Code generated by Konfig (https://konfigthis.com); DO NOT EDIT.

package nuitee

import (
	"encoding/json"
)

// BookResponse struct for BookResponse
type BookResponse struct {
	Data *BookResponseData `json:"data,omitempty"`
	// guests loyalty level granting them discounts and benefit
	GuestLevel *int32 `json:"guestLevel,omitempty"`
	Sandbox *bool `json:"sandbox,omitempty"`
}

// NewBookResponse instantiates a new BookResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBookResponse() *BookResponse {
	this := BookResponse{}
	return &this
}

// NewBookResponseWithDefaults instantiates a new BookResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBookResponseWithDefaults() *BookResponse {
	this := BookResponse{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *BookResponse) GetData() BookResponseData {
	if o == nil || isNil(o.Data) {
		var ret BookResponseData
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BookResponse) GetDataOk() (*BookResponseData, bool) {
	if o == nil || isNil(o.Data) {
    return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *BookResponse) HasData() bool {
	if o != nil && !isNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given BookResponseData and assigns it to the Data field.
func (o *BookResponse) SetData(v BookResponseData) {
	o.Data = &v
}

// GetGuestLevel returns the GuestLevel field value if set, zero value otherwise.
func (o *BookResponse) GetGuestLevel() int32 {
	if o == nil || isNil(o.GuestLevel) {
		var ret int32
		return ret
	}
	return *o.GuestLevel
}

// GetGuestLevelOk returns a tuple with the GuestLevel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BookResponse) GetGuestLevelOk() (*int32, bool) {
	if o == nil || isNil(o.GuestLevel) {
    return nil, false
	}
	return o.GuestLevel, true
}

// HasGuestLevel returns a boolean if a field has been set.
func (o *BookResponse) HasGuestLevel() bool {
	if o != nil && !isNil(o.GuestLevel) {
		return true
	}

	return false
}

// SetGuestLevel gets a reference to the given int32 and assigns it to the GuestLevel field.
func (o *BookResponse) SetGuestLevel(v int32) {
	o.GuestLevel = &v
}

// GetSandbox returns the Sandbox field value if set, zero value otherwise.
func (o *BookResponse) GetSandbox() bool {
	if o == nil || isNil(o.Sandbox) {
		var ret bool
		return ret
	}
	return *o.Sandbox
}

// GetSandboxOk returns a tuple with the Sandbox field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BookResponse) GetSandboxOk() (*bool, bool) {
	if o == nil || isNil(o.Sandbox) {
    return nil, false
	}
	return o.Sandbox, true
}

// HasSandbox returns a boolean if a field has been set.
func (o *BookResponse) HasSandbox() bool {
	if o != nil && !isNil(o.Sandbox) {
		return true
	}

	return false
}

// SetSandbox gets a reference to the given bool and assigns it to the Sandbox field.
func (o *BookResponse) SetSandbox(v bool) {
	o.Sandbox = &v
}

func (o BookResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if !isNil(o.GuestLevel) {
		toSerialize["guestLevel"] = o.GuestLevel
	}
	if !isNil(o.Sandbox) {
		toSerialize["sandbox"] = o.Sandbox
	}
	return json.Marshal(toSerialize)
}

type NullableBookResponse struct {
	value *BookResponse
	isSet bool
}

func (v NullableBookResponse) Get() *BookResponse {
	return v.value
}

func (v *NullableBookResponse) Set(val *BookResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableBookResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableBookResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBookResponse(val *BookResponse) *NullableBookResponse {
	return &NullableBookResponse{value: val, isSet: true}
}

func (v NullableBookResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBookResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


