/*
 * Lite API
 * lite api hotel booking api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.nuitee.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.nuitee.client.model.GetHotelRatesResponseDataInnerRoomTypesInnerRatesInnerCancellationPolicies;
import com.konfigthis.nuitee.client.model.GetHotelRatesResponseDataInnerRoomTypesInnerRatesInnerRetailRate;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for GetHotelRatesResponseDataInnerRoomTypesInnerRatesInner
 */
public class GetHotelRatesResponseDataInnerRoomTypesInnerRatesInnerTest {
    private final GetHotelRatesResponseDataInnerRoomTypesInnerRatesInner model = new GetHotelRatesResponseDataInnerRoomTypesInnerRatesInner();

    /**
     * Model tests for GetHotelRatesResponseDataInnerRoomTypesInnerRatesInner
     */
    @Test
    public void testGetHotelRatesResponseDataInnerRoomTypesInnerRatesInner() {
        // TODO: test GetHotelRatesResponseDataInnerRoomTypesInnerRatesInner
    }

    /**
     * Test the property 'rateId'
     */
    @Test
    public void rateIdTest() {
        // TODO: test rateId
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'maxOccupancy'
     */
    @Test
    public void maxOccupancyTest() {
        // TODO: test maxOccupancy
    }

    /**
     * Test the property 'retailRate'
     */
    @Test
    public void retailRateTest() {
        // TODO: test retailRate
    }

    /**
     * Test the property 'cancellationPolicies'
     */
    @Test
    public void cancellationPoliciesTest() {
        // TODO: test cancellationPolicies
    }

}
