/*
 * Lite API
 * lite api hotel booking api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.nuitee.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.nuitee.client.model.BookResponseDataGuestInfo;
import com.konfigthis.nuitee.client.model.RetrieveResponseDataBookedRoomsInner;
import com.konfigthis.nuitee.client.model.RetrieveResponseDataCancellationPolicies;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for RetrieveResponseData
 */
public class RetrieveResponseDataTest {
    private final RetrieveResponseData model = new RetrieveResponseData();

    /**
     * Model tests for RetrieveResponseData
     */
    @Test
    public void testRetrieveResponseData() {
        // TODO: test RetrieveResponseData
    }

    /**
     * Test the property 'bookingId'
     */
    @Test
    public void bookingIdTest() {
        // TODO: test bookingId
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'hotelConfirmationCode'
     */
    @Test
    public void hotelConfirmationCodeTest() {
        // TODO: test hotelConfirmationCode
    }

    /**
     * Test the property 'checkin'
     */
    @Test
    public void checkinTest() {
        // TODO: test checkin
    }

    /**
     * Test the property 'checkout'
     */
    @Test
    public void checkoutTest() {
        // TODO: test checkout
    }

    /**
     * Test the property 'bookedRooms'
     */
    @Test
    public void bookedRoomsTest() {
        // TODO: test bookedRooms
    }

    /**
     * Test the property 'guestInfo'
     */
    @Test
    public void guestInfoTest() {
        // TODO: test guestInfo
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'cancellationPolicies'
     */
    @Test
    public void cancellationPoliciesTest() {
        // TODO: test cancellationPolicies
    }

}
