//
// BookResponseDataHotelAddress.swift
//
// Generated by Konfig
// https://konfigthis.com
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct BookResponseDataHotelAddress: Codable, JSONEncodable, Hashable {

    public var line1: String?
    public var line2: String?
    public var city: String?
    public var postalCode: String?
    public var region: String?
    public var country: String?
    public var countryName: String?

    public init(line1: String? = nil, line2: String? = nil, city: String? = nil, postalCode: String? = nil, region: String? = nil, country: String? = nil, countryName: String? = nil) {
        self.line1 = line1
        self.line2 = line2
        self.city = city
        self.postalCode = postalCode
        self.region = region
        self.country = country
        self.countryName = countryName
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case line1
        case line2
        case city
        case postalCode
        case region
        case country
        case countryName
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(line1, forKey: .line1)
        try container.encodeIfPresent(line2, forKey: .line2)
        try container.encodeIfPresent(city, forKey: .city)
        try container.encodeIfPresent(postalCode, forKey: .postalCode)
        try container.encodeIfPresent(region, forKey: .region)
        try container.encodeIfPresent(country, forKey: .country)
        try container.encodeIfPresent(countryName, forKey: .countryName)
    }
}

