//
// BookResponseDataBookedRoomsInner.swift
//
// Generated by Konfig
// https://konfigthis.com
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct BookResponseDataBookedRoomsInner: Codable, JSONEncodable, Hashable {

    public var roomType: BookResponseDataBookedRoomsInnerRoomType?
    public var adults: Int?
    public var children: Int?
    public var rate: BookResponseDataBookedRoomsInnerRate?

    public init(roomType: BookResponseDataBookedRoomsInnerRoomType? = nil, adults: Int? = nil, children: Int? = nil, rate: BookResponseDataBookedRoomsInnerRate? = nil) {
        self.roomType = roomType
        self.adults = adults
        self.children = children
        self.rate = rate
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case roomType
        case adults
        case children
        case rate
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(roomType, forKey: .roomType)
        try container.encodeIfPresent(adults, forKey: .adults)
        try container.encodeIfPresent(children, forKey: .children)
        try container.encodeIfPresent(rate, forKey: .rate)
    }
}

