//
// BookResponseDataHotel.swift
//
// Generated by Konfig
// https://konfigthis.com
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct BookResponseDataHotel: Codable, JSONEncodable, Hashable {

    public var hotelId: String?
    public var name: String?
    public var starRating: Int?
    public var address: BookResponseDataHotelAddress?
    public var location: BookResponseDataHotelLocation?

    public init(hotelId: String? = nil, name: String? = nil, starRating: Int? = nil, address: BookResponseDataHotelAddress? = nil, location: BookResponseDataHotelLocation? = nil) {
        self.hotelId = hotelId
        self.name = name
        self.starRating = starRating
        self.address = address
        self.location = location
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case hotelId
        case name
        case starRating
        case address
        case location
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(hotelId, forKey: .hotelId)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(starRating, forKey: .starRating)
        try container.encodeIfPresent(address, forKey: .address)
        try container.encodeIfPresent(location, forKey: .location)
    }
}

