//
// CancelResponse.swift
//
// Generated by Konfig
// https://konfigthis.com
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CancelResponse: Codable, JSONEncodable, Hashable {

    public var bookingId: String?
    public var cancellationFee: Int?
    public var currency: String?
    public var refundAmount: Double?
    public var status: String?

    public init(bookingId: String? = nil, cancellationFee: Int? = nil, currency: String? = nil, refundAmount: Double? = nil, status: String? = nil) {
        self.bookingId = bookingId
        self.cancellationFee = cancellationFee
        self.currency = currency
        self.refundAmount = refundAmount
        self.status = status
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case bookingId
        case cancellationFee = "cancellation_fee"
        case currency
        case refundAmount = "refund_amount"
        case status
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(bookingId, forKey: .bookingId)
        try container.encodeIfPresent(cancellationFee, forKey: .cancellationFee)
        try container.encodeIfPresent(currency, forKey: .currency)
        try container.encodeIfPresent(refundAmount, forKey: .refundAmount)
        try container.encodeIfPresent(status, forKey: .status)
    }
}

