//
// GetHotelRatesResponseDataInnerRoomTypesInner.swift
//
// Generated by Konfig
// https://konfigthis.com
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetHotelRatesResponseDataInnerRoomTypesInner: Codable, JSONEncodable, Hashable {

    public var roomTypeId: String?
    public var maxOccupancy: Int?
    public var rates: [GetHotelRatesResponseDataInnerRoomTypesInnerRatesInner]?

    public init(roomTypeId: String? = nil, maxOccupancy: Int? = nil, rates: [GetHotelRatesResponseDataInnerRoomTypesInnerRatesInner]? = nil) {
        self.roomTypeId = roomTypeId
        self.maxOccupancy = maxOccupancy
        self.rates = rates
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case roomTypeId
        case maxOccupancy
        case rates
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(roomTypeId, forKey: .roomTypeId)
        try container.encodeIfPresent(maxOccupancy, forKey: .maxOccupancy)
        try container.encodeIfPresent(rates, forKey: .rates)
    }
}

