//
// ListHotelsResponse.swift
//
// Generated by Konfig
// https://konfigthis.com
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ListHotelsResponse: Codable, JSONEncodable, Hashable {

    public var data: [ListHotelsResponseDataInner]?
    public var total: Int?

    public init(data: [ListHotelsResponseDataInner]? = nil, total: Int? = nil) {
        self.data = data
        self.total = total
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case data
        case total
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(data, forKey: .data)
        try container.encodeIfPresent(total, forKey: .total)
    }
}

