//
// PrebookRequest.swift
//
// Generated by Konfig
// https://konfigthis.com
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PrebookRequest: Codable, JSONEncodable, Hashable {

    /** session id retrievied from rates response */
    public var sessionId: String?
    /** rate id retrieved from rates response */
    public var rateId: String

    public init(sessionId: String? = nil, rateId: String) {
        self.sessionId = sessionId
        self.rateId = rateId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case sessionId
        case rateId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(sessionId, forKey: .sessionId)
        try container.encode(rateId, forKey: .rateId)
    }
}

