//
// PrebookResponseDataRoomTypesInnerRatesInnerRetailRate.swift
//
// Generated by Konfig
// https://konfigthis.com
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PrebookResponseDataRoomTypesInnerRatesInnerRetailRate: Codable, JSONEncodable, Hashable {

    public var total: [GetHotelRatesResponseDataInnerRoomTypesInnerRatesInnerRetailRateTotalInner]?
    public var taxesAndFees: [GetHotelRatesResponseDataInnerRoomTypesInnerRatesInnerRetailRateTaxesAndFeesInner]?

    public init(total: [GetHotelRatesResponseDataInnerRoomTypesInnerRatesInnerRetailRateTotalInner]? = nil, taxesAndFees: [GetHotelRatesResponseDataInnerRoomTypesInnerRatesInnerRetailRateTaxesAndFeesInner]? = nil) {
        self.total = total
        self.taxesAndFees = taxesAndFees
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case total
        case taxesAndFees
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(total, forKey: .total)
        try container.encodeIfPresent(taxesAndFees, forKey: .taxesAndFees)
    }
}

