name: "konfig-lint-openapi-spec"
on: # rebuild any PRs or target branches
  pull_request:
  push:
    branches:
      - main # replace this with your list of target branches
jobs:
  konfig-lint-openapi-spec:
    runs-on: ubuntu-latest
    env:
      CLI_VERSION: 1.0.173
    steps:
      - uses: actions/checkout@v3
      - name: Cache node_modules
        id: cache-npm
        uses: actions/cache@v3
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.CLI_VERSION }}
      - name: Install Konfig CLI
        run: npm install -g konfig-cli@$CLI_VERSION
      - name: Initialize Linting Rules
        run: konfig init -s
      - name: Lint OpenAPI Spec
        run: konfig lint
      # Optionally add breaking change detection
      # - name: Detect breaking change
      #   run: konfig detect-breaking-change -m main # replace main with the name of your base branch